config/routes.rb
Rails.application.routes.draw do
  root 'about#index'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Students
  resources :students
  delete 'reset_answers', to: 'students#reset_answers'

  # Levels
  resources :levels
  get "download_pdf", to: "levels#download_pdf"

  # Presentations
  resources :about, only: %i[index]
  post 'about/paginate'

  # Questions
  resources :questions, only: %i[index show]
  post 'submit_question', to: 'questions#submit'
  get 'previous_question', to: 'questions#back'
  patch 'resubmit_question', to: 'questions#resubmit'
  get 'partial_results', to: 'questions#partial_results'
  delete 'reset_level', to: 'questions#reset_level'
  get 'discover', to: 'questions#discover'
  get 'results', to: 'questions#results'
  get 'error', to: 'questions#error'

  # Comments
  resources :comments, only: %i[index new create]

  # Likes
  post 'create_like', to: 'likes#create'
  delete 'destroy_like', to: 'likes#destroy'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id             :bigint           not null, primary key
#  code           :string           not null
#  correct_answer :string           not null
#  options        :jsonb            not null
#  text           :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  level_id       :bigint           not null
#
# Indexes
#
#  index_questions_on_code      (code) UNIQUE
#  index_questions_on_level_id  (level_id)
#
# Foreign Keys
#
#  fk_rails_...  (level_id => levels.id)
#
class Question < ApplicationRecord
  validates :code, uniqueness: true
  validates :correct_answer, :options, :text, presence: true

  belongs_to :level

  has_many :question_answers, dependent: :destroy
  has_one :course, through: :level, source: :course

  def number
    code.sub(/[A-Z]/, '').chars.first
  end

  def self.next(question)
    return if question.nil?

    if question.number.to_i < 5
      new_code = question.code.sub("Q#{question.number}", "Q#{question.number.to_i + 1}")
      Question.find_by(code: new_code)
    else
      new_level = Level.next(question.level)
      unless new_level.nil?
        new_code = "Q1L#{new_level.number}C#{question.course.number}"
        Question.find_by(code: new_code)
      end
    end
  end

  def self.back(question)
    return if question.nil?

    if question.number.to_i > 1
      new_code = question.code.sub("Q#{question.number}", "Q#{question.number.to_i - 1}")
      Question.find_by(code: new_code)
    else
      new_level = Level.back(question.level)
      unless new_level.nil?
        new_code = "Q5L#{new_level.number}C#{question.course.number}"
        Question.find_by(code: new_code)
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticateStudent
  before_action :set_question, only: %i[show back]
  before_action :question_params, only: %i[submit resubmit]
  before_action :set_level, only: %i[partial_results reset_level discover]

  def index
    @course = current_user.my_course
    @last = current_user.last_answered
    if @last.nil?
      @level = Level.find_by(code: "L1C#{@course.number}")
      @question = @level.questions.order(:code).first
    else
      @question = Question.next(@last.question)
      redirect_to(results_path) and return if @question.nil?

      @level = @question.level unless @question.nil?
    end
  end

  def show
    @question = nil if all_questions_answered
    redirect_to(results_path) and return if @question.nil?

    @level = @question.level
    @count = current_user.answers(@level)
    @next_question = Question.next(@question)
    redirect_to(partial_results_path(id: @level)) and return if @count == 5
  end

  def submit
    @question = Question.find(question_params[:id])
    if !@question.nil? && !create_question_answer
      redirect_to(error_path) and return
    else
      @level = @question.level
      @count = current_user.answers(@level)

      if @count == 5
        redirect_to(partial_results_path(id: @level)) and return
      else
        @next_question = Question.next(@question)
        redirect_to(question_path(@next_question))
      end
    end
  end

  def back
    @prev_question = Question.back(@question)
    redirect_to(question_path(@prev_question))
  end

  def resubmit
    @question = Question.find(question_params[:id])
    if !@question.nil? && !patch_question_answer
      redirect_to(error_path) and return
    else
      @level = @question.level
      @count = current_user.answers(@level)
      @next_question = Question.next(@question)
      redirect_to(question_path(@next_question))
    end
  end

  def partial_results
    @course = @level.course
    @correct_answers = current_user.correct_answers(@level)
    redirect_to(questions_path) and return if @course.id != current_user.my_course.id
  end

  def reset_level
    current_user.destroy_question_answers(@level)
    @question = @level.questions.order(:code).first

    redirect_to(question_path(@question))
  end

  def discover
    @next_level = Level.next(@level)
    @next_question = @next_level.questions.order(:code).first unless @next_level.nil?
  end

  def results
    redirect_to(questions_path) and return unless all_questions_answered
  end

  def error; end

  private

  def set_question
    @question = Question.find_by(id: params[:id])
    find_answer(@question)
  end

  def find_answer(question)
    return if question.nil?

    @selected = current_user.question_answers.find_by(question:)
    @answer = @selected.answer if @selected&.question&.id == question.id
  end

  def set_level
    @level = Level.find_by(id: params[:id])
  end

  def create_question_answer
    return if QuestionAnswer.find_by(question: @question, user: current_user)

    QuestionAnswer.new(user: current_user, question: @question, answer: question_params[:answer]).save
  end

  def patch_question_answer
    @question_answer = QuestionAnswer.find_by(question: @question, user: current_user)
    @question_answer&.update(answer: question_params[:answer])
  end

  def question_params
    params.require(:question).permit(:id, :answer)
  end

  def all_questions_answered
    current_user.question_answers.count == 20
  end

  def authenticateStudent
    redirect_to(root_path) if current_user.teacher?
  end
end

app/views/questions/_form.html.haml
- if @level&.image_url
  .mt-28
    .image-question.text-center
      = image_tag @level.image_url, class: "m-auto"
    .image-source
      %span.italic= "Tomado de: "
      %a(href="#{@level.image_source}")= "#{@level.image_source}"
- if @level&.video_url
  -# .text-3xl= @level&.video_url
  -if @level.code == 'L1C5' || @level.code == 'L1C3'
    .mt-28
      .image-question
        %iframe{:allow => "autoplay", :height => "480", :src => "#{@level.video_url}", class: "w-full" }
      .image-source
        %span.italic Tomado de:
        %a(href="#{@level.video_source}")= "#{@level.video_source}"
  -else
    .mt-28
      .image-question
        %iframe.mx-auto.border-8.border-blue-300{allow: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture", allowfullscreen: "", frameborder: "0", src: @level&.video_url, title: "YouTube video player", class: "w-full h-96"}
      .image-source
        %span.italic Tomado de:
        %a(href="#{@level.video_source}")= "#{@level.video_source}"
- if @level&.text
  .mt-10
    %div{ class: "#{@level.code == 'L2C5'|| @level.code == 'L2C3' ? 'lyrics' : 'text-question' }"}
      = @level.text.html_safe
    .text-source.mt-3
      %span.italic Tomado de:
      %a(href="#{@level.text_source.html_safe}")= "#{@level.text_source.html_safe}"
.mt-5
  %h2.mb-5.text-lg.question-level.font-bold.text-neutral-3#question= "(#{question.number}) - #{question.text.html_safe}"
  = form_with model: question, url: @answer.nil? ? submit_question_path : resubmit_question_path, method: @answer.nil? ? :post : :patch do |f|
    = f.hidden_field :id
    -# .font-bold= question.correct_answer
    - question.options.each_pair do |k, v|
      .form-fields.mb-5
        %span.font-bold.text-neutral-3.pr-1= "(#{k.upcase})"
        - if !@answer.nil? && @answer == k
          = f.radio_button :answer, k, checked: true, required: true
        - else
          = f.radio_button :answer, k, required: true
        = f.label :answer, v.html_safe, class: "pl-1 #{'question-option' if question.code == 'Q1L1C3' || question.code == 'Q2L1C5'}"
    .mt-5.flex.justify-center
      - unless question.code.include?('Q1L1')
        = link_to previous_question_path(id: question), class: "mr-12 w-fit text-center link-2" do
          = image_tag "back.svg", class: "icon m-auto animated-back"
          %span.text-xs.font-bold.text-indigo-600 Atrás
      %button.w-fit.text-center.relative.link-2{type: "button"}
        = f.submit "", class: "absolute top-0 bottom-0 w-full cursor-pointer"
        = image_tag "next.svg", class: "icon m-auto"
        %span.text-xs.font-bold.text-indigo-600 Siguiente
#number.opacity-0= question.number
:javascript
  setTimeout(() => {
    const number = document.getElementById('number').innerHTML
    if (number !== '1') {
      document.getElementById('question').scrollIntoView({ behavior: 'smooth'});
    }
  }, 200);

app/views/questions/discover.html.haml
.card
  .card-body
    .con
      %h1.mb-3.text-neutral-3.text-2xl.text-center.comic= t("discover.L#{@level.number}.title")
      %div
        - if @next_question.nil?
          %h1.mb-3.text-3xl.text-center.comic ¡Felicidades has terminado!
          = image_tag "discover_L#{@level.number}.png", class: "m-auto opacity-0", id: "alcaravan"
        - else
          - if @level.number == "1"
            %iframe{:allow => "autoplay", :height => "480", :src => "https://drive.google.com/file/d/18QMz07l--6etSysMepnfR-dWqyKSv8K8/preview", class: "w-full" }
          - else 
            = image_tag "discover_L#{@level.number}.png", class: "m-auto"

      .image-source
        - unless @next_question.nil?
          %span.italic= "Tomado de: "
          %a{ href: t("discover.L#{@level.number}.image_source") }= t("discover.L#{@level.number}.image_source")
      %p.mt-3= t("discover.L#{@level.number}.text")
      .mt-5.flex.justify-center
        - if @next_question.nil?
          .mt-5.flex.justify-center
            %button{:onclick => "playAudio()", class: "mr-12 w-fit text-center link-2"}
              = image_tag "play.svg", class: "icon m-auto animated-play"
              %span.text-xs.font-bold.text-indigo-600 Escuchar a El Alcaraván
            = link_to results_path, class: "w-fit text-center link-2" do
              = image_tag "next.svg", class: "icon m-auto animated-back"
              %span.text-xs.font-bold.text-indigo-600 Siguiente
        - else
          -# = link_to 'Continuar', question_path(@next_question), class: 'btn btn-primary w-fit'
          = link_to question_path(@next_question), class: "w-fit text-center link-2" do
            = image_tag "next.svg", class: "icon m-auto"
            %span.text-xs.font-bold.text-indigo-600 Siguiente
- if @next_question.nil?
  :javascript
    setTimeout(() => {
      const image = document.getElementById('alcaravan');
      if (image) {
        image.classList.replace('opacity-0', 'opacity-1');
      }
    }, 50);

:javascript
  function playAudio() {
    if (!document.getElementById('audio')) {
      const audio = document.createElement('audio');
      audio.setAttribute('src', 'alcaravan.mp3');
      audio.setAttribute('autoplay', 'autoplay');
      audio.setAttribute('muted', 'muted');
      audio.id = 'audio';
      document.body.appendChild(audio);
      audio.play();
    }
  };

app/views/questions/error.html.haml
.card
  .card-body
    .con
      .card-header.text-center
        %h1 ¡Ups! Ha habido un error.

app/views/questions/index.html.haml
.card
  .card-body
    .con
      .card-header.text-center.relative
        %h1.text-4xl.comic.relative.z-10= @course.name
        .class-number
          = image_tag "course_#{@course.number}.svg", class: "w-[100px]"
      .text-center.mt-12
        %span Preguntas contestadas:
        %span= "#{current_user.answers(@level)}/5"
        .font-bold= "Pregunta ##{@question.number} - Nivel ##{@level.number}"
      .flex.items-center.w-fit.m-auto
        .mt-5
          = link_to question_path(@question), class: "w-fit text-center link-2 animated-next" do
            = image_tag "next.svg", class: "icon m-auto"
            %span.text-xs.font-bold.text-indigo-600 Continuar

app/views/questions/next.turbo_stream.haml
= turbo_stream.update "questions" do
  - if @question.nil?
    = render "finish"
  - else
    - if @error.nil?
      = render "form", question: @next_question
    - else
      %p= @error

app/views/questions/partial_results.html.haml
.card
  .card-body
    .con
      .card-header.text-center
        %h1.comic.text-3xl= "Resultados del nivel #{@level.number}"
      .mt-5.flex.flex-col.items-center.opacity-0#results
        .text-center
          %p.mb-3.text-xl= "Preguntas correctas: #{@correct_answers}/5"
        - if @correct_answers >= 4
          .image-llanerito
            = image_tag "good.svg", alt: 'globo', class: 'balloon'
            = image_tag "llanerito.png", class: "boy", id: "alcaravan"
          #good
          %p.text-xl.my-5¡Muy bien haz logrado avanzar!
          = link_to discover_path(id: @level), class: "w-fit text-center link-2" do
            = image_tag "next.svg", class: "icon m-auto"
            %span.text-xs.font-bold.text-indigo-600 Siguiente
        - else
          #bad
          .balloon
          .image-llanerito
            = image_tag "#{@level.code}.svg", alt: 'globo', class: 'balloon'
            = image_tag "llanerito.png", class: "boy", id: "alcaravan"
          %p.text-xl.my-5 ¡Vuelve a intentarlo, puedes lograrlo!
          = button_to reset_level_path(id: @level), class: "w-fit text-center link-2", method: :delete do
            = image_tag "next.svg", class: "icon m-auto animated-next"
            %span.text-xs.font-bold.text-indigo-600 Siguiente
      .mt-5.flex.justify-center
        %button{:onclick => "showResults()", class: "w-fit text-center link-2", id: "display-results"}
          = image_tag "question.svg", class: "icon m-auto animated-play"
          %span.text-xs.font-bold.text-indigo-600 Descubrir resultados
:javascript
  function showResults() {
    document.getElementById('results').classList.replace('opacity-0', 'opacity-1');
    const displayResults = document.getElementById('display-results');
    displayResults.classList.add('vanish');
    setTimeout(() => { 
      displayResults.classList.add('shrink');
      displayResults.remove();
    }, 1000);
    if (!document.getElementById('audio')) {
      const audio = document.createElement('audio');
      if (document.getElementById('good')) {
        audio.setAttribute('src', "good.mp3");
      } else {
        audio.setAttribute('src', "A#{@level.code}.ogg");
      }
      audio.setAttribute('autoplay', 'autoplay');
      audio.setAttribute('muted', 'muted');
      audio.id = 'audio';
      document.body.appendChild(audio);
      audio.play();
    }
  }

app/views/questions/results.html.haml
.card
  .card-body
    .con
      .card-header
        .flex.item-center.justify-center
          = image_tag "smiley.svg", class: "mr-2 icon"
          %h1 ¡Felicidades, has terminado todo el curso!
          = image_tag "trophy.svg", class: "ml-2 icon"

app/views/questions/show.html.haml
.card
  .card-body.relative
    .card-header.flex.-rotate-12.absolute
      %h1.text-5xl.comic Nivel
      = image_tag "level_#{@level.number}.svg", class: "ml-2 icon"
    .con
      = render "form", question: @question