config/routes.rb
Rails.application.routes.draw do
  root 'about#index'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Students
  resources :students
  delete 'reset_answers', to: 'students#reset_answers'

  # Levels
  resources :levels
  get "download_pdf", to: "levels#download_pdf"

  # Presentations
  resources :about, only: %i[index]
  post 'about/paginate'

  # Questions
  resources :questions, only: %i[index show]
  post 'submit_question', to: 'questions#submit'
  get 'previous_question', to: 'questions#back'
  patch 'resubmit_question', to: 'questions#resubmit'
  get 'partial_results', to: 'questions#partial_results'
  delete 'reset_level', to: 'questions#reset_level'
  get 'discover', to: 'questions#discover'
  get 'results', to: 'questions#results'
  get 'error', to: 'questions#error'

  # Comments
  resources :comments, only: %i[index new create]

  # Likes
  post 'create_like', to: 'likes#create'
  delete 'destroy_like', to: 'likes#destroy'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @students = current_user.course_teacher.course.students.order(first_name: :asc)
  end

  def show
    @student = User.student.find(params[:id])
    @level = Level.find(params[:level_id])
    respond_to do |format|
      format.html
      format.pdf do
        render(pdf: "Invoice No. #{@student.id}",
               page_size: 'letter',
               template: 'students/show',
               layout: 'pdf',
               formats: [:html],
               orientation: 'portrait',
               lowquality: true,
               zoom: 1,
               dpi: 75,
               encoding: 'utf8')
      end
    end
  end

  def reset_answers
    @student = User.student.find(params[:id])
    @student.question_answers.destroy_all
    redirect_to students_path
  end
end

app/views/students/index.html.haml
.card
  .card-body
    .card-header.flex.items-center
      %h2.text-3xl.comic Estudiantes
      = image_tag "course_#{current_user.course.number}.svg", class: "ml-1 icon"
    .grid.grid-cols-12.font-semibold.text-base.py-4
      .col-span-2.text-left Nombre
      .col-span-2.text-left Nivel 1
      .col-span-2.text-left Nivel 2
      .col-span-2.text-left Nivel 3
      .col-span-2.text-left Nivel 4
      .col-span-2.text-left Reiniciar
    -@students.map do |student|
      .grid.grid-cols-12.py-4.px-2.my-3.rounded.bg-yellow-100.border-2.border-neutral-900.text-neutral-3{class: 'hover:bg-yellow-200'}
        .col-span-2.text-left.font-bold= student.full_name.capitalize
        - student.course_student.course.levels.each do |level|
          -if student.answers(level) > 0
            .col-span-2.text-left
              -# %span
                = link_to student_path(id: student, level_id: level, format:'pdf') , target: '_blank' do
                  = image_tag 'pdf.svg', alt: 'Pdf icon', class: 'w-6 h-6'
              %span= "#{student.correct_answers(level)}/#{level.questions.count}"
          -else
            .col-span-2.text-left
              %span N/A
        -if student.question_answers.empty?
          .col-span-2
        -else
          .col-span-2.text-left
            = button_to reset_answers_path(id: student), class: "w-fit text-center link-2", method: :delete do
              = image_tag "reset.svg", class: "icon m-auto animated-next"

app/views/students/show.html.haml
%div
  %div= "Nombre: #{@student.full_name}"
  %div= "Grado: #{@level.course.name}"
%br/
%div
  %div= @level.text
  %div= "Tomado de: #{@level.text_source}"
%br/
-@level.questions.each_with_index do |question, index|
  %div
    %div= "#{index + 1}. #{question.text.html_safe}"
    - question.options.each do |key, value|
      %div="#{key}. #{value.html_safe}"
    %div= "la respuesta del estudiante es #{@student.my_answer(question)}"
    %div= "la respuesta correcta es #{question.correct_answer}"
  %br/