config/routes.rb
Rails.application.routes.draw do
  root 'about#index'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Students
  resources :students
  delete 'reset_answers', to: 'students#reset_answers'

  # Levels
  resources :levels
  get "download_pdf", to: "levels#download_pdf"

  # Presentations
  resources :about, only: %i[index]
  post 'about/paginate'

  # Questions
  resources :questions, only: %i[index show]
  post 'submit_question', to: 'questions#submit'
  get 'previous_question', to: 'questions#back'
  patch 'resubmit_question', to: 'questions#resubmit'
  get 'partial_results', to: 'questions#partial_results'
  delete 'reset_level', to: 'questions#reset_level'
  get 'discover', to: 'questions#discover'
  get 'results', to: 'questions#results'
  get 'error', to: 'questions#error'

  # Comments
  resources :comments, only: %i[index new create]

  # Likes
  post 'create_like', to: 'likes#create'
  delete 'destroy_like', to: 'likes#destroy'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  comment_id :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_likes_on_comment_id  (comment_id)
#  index_likes_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (comment_id => comments.id)
#  fk_rails_...  (user_id => users.id)
#
class Like < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :like_params, only: %i[create]
  before_action :like_params_on_destroy, only: %i[destroy]

  def create
    @comment = Comment.find_by(id: like_params[:comment_id])
    @like = Like.create(comment_id: @comment.id, user_id: current_user.id) unless @comment.nil?

    respond_to do |format|
      format.turbo_stream
    end
  end

  def destroy
    @like = Like.find_by(id: like_params_on_destroy[:id])
    @comment = @like.comment
    @like.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def like_params
    params.require(:like).permit(:comment_id)
  end

  def like_params_on_destroy
    params.require(:like).permit(:id)
  end
end

app/views/likes/_form.html.haml
= turbo_frame_tag comment do
  - unless comment.nil?
    - liked = current_user.comment_liked?(comment)
    .likes.mr-3
      = form_with model: Like.new, url: liked ? destroy_like_path : create_like_path, method: liked ? :delete : :post do |f|
        - if liked
          = f.hidden_field :id, value: liked.id
        - else
          = f.hidden_field :comment_id, value: comment.id
        .flex.items-center
          %button.mr-2.text-center.relative{type: "button", onclick: "playAudio()"}
            = f.submit "", class: "absolute top-0 bottom-0 left-0 w-full cursor-pointer"
            - if liked
              = image_tag "filled_heart.svg", class: "w-[24px] m-auto"
            - else
              = image_tag "empty_heart.svg", class: "w-[24px] m-auto"
          %span.text-lg= comment.likes.count
:javascript
    console.log('Load');
  function playAudio() {
    const audio = document.getElementById('audio');
    if (audio) {
      console.log('Click');
      audio.play();
    }
  };

app/views/likes/create.turbo_stream.haml
= turbo_stream.update @comment do
  = render "form", comment: @comment

app/views/likes/destroy.turbo_stream.haml
= turbo_stream.update @comment do
  = render "form", comment: @comment