config/routes.rb
Rails.application.routes.draw do
  root 'about#index'

  # Dashboard
  resources :dashboard, only: %i[index]

  # Students
  resources :students
  delete 'reset_answers', to: 'students#reset_answers'

  # Levels
  resources :levels
  get "download_pdf", to: "levels#download_pdf"

  # Presentations
  resources :about, only: %i[index]
  post 'about/paginate'

  # Questions
  resources :questions, only: %i[index show]
  post 'submit_question', to: 'questions#submit'
  get 'previous_question', to: 'questions#back'
  patch 'resubmit_question', to: 'questions#resubmit'
  get 'partial_results', to: 'questions#partial_results'
  delete 'reset_level', to: 'questions#reset_level'
  get 'discover', to: 'questions#discover'
  get 'results', to: 'questions#results'
  get 'error', to: 'questions#error'

  # Comments
  resources :comments, only: %i[index new create]

  # Likes
  post 'create_like', to: 'likes#create'
  delete 'destroy_like', to: 'likes#destroy'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }
end

app/views/layouts/_navbar.html.haml
.navbar
  .inner-navbar
    = link_to root_path do
      .flex.items-center
        .rounded-full.border-2.border-black
          = image_tag "birdIcon.svg", class: "w-12"
        .ml-3.pt-2
          %span.font-bold.cursive.text-yellow-400.text-4xl Alcaraván
    %div
      - if current_user.student?
        %ul.grid.grid-cols-3.gap-3
          %li.link.self-end
            = link_to about_index_path, class: "mt-1 text-center text-xs" do
              = image_tag "home.svg", class: "icon mx-auto animated-icon animated-icon-step"
              %span.text-indigo-600.font-bold= "Inicio"
          %li.link.self-end
            = link_to questions_path, class: "mt-1 text-center text-xs" do
              = image_tag "book.svg", class: "icon mx-auto animated-icon animated-icon-step"
              %span.text-indigo-600.font-bold= "Preguntas"
          %li.link.self-end
            = link_to comments_path, class: "mt-1 text-center text-xs" do
              = image_tag "forum.svg", class: "icon mx-auto animated-icon animated-icon-step"
              %span.text-indigo-600.font-bold= "Foro"
      - else
        %ul.grid.grid-cols-4.gap-3
          %li.link.self-end
            = link_to about_index_path, class: "mt-1 text-center text-xs" do
              = image_tag "home.svg", class: "icon mx-auto animated-icon animated-icon-step"
              %span.text-indigo-600.font-bold= "Inicio"
          %li.link.self-end
            = link_to students_path, class: "mt-1 text-center text-xs" do
              = image_tag "pencil.svg", class: "icon w-[2rem] mx-auto animated-icon animated-icon-step"
              %span.text-indigo-600.font-bold= "Alumnos"
          %li.link.self-end
            = link_to levels_path, class: "mt-1 text-center text-xs" do
              = image_tag "document.svg", class: "icon mx-auto animated-icon animated-icon-step"
              %span.text-indigo-600.font-bold= "Lecturas"
          %li.link.self-end
            = link_to comments_path, class: "mt-1 text-center text-xs" do
              = image_tag "forum.svg", class: "icon mx-auto animated-icon animated-icon-step"
              %span.text-indigo-600.font-bold= "Foro"

    .flex.items-center
      .mr-5.flex.items-center
        .rounded-full.w-fit.p-2.mr-2
          = image_tag "waving.svg", class: "wave animated-icon"
        %span.greeting{style: "animation: typing 2s steps(#{current_user.full_name.length + 5}), blink 1s infinite step-end alternate; width: #{current_user.full_name.length + 5}ch;"}= "¡Hola #{current_user.full_name.capitalize.titleize}!"
        -# %span.comic.text-xs= t(current_user.role)
      .link
        = link_to dashboard_index_path, class: "text-center icon animated-icon" do
          = image_tag "logout.svg"
          %span.text-xs.text-red-600.font-bold Salir

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Alcaraván
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    -# = favicon_link_tag asset_path('bird.ico')
  %body.bg-gradient
    %div= render 'layouts/navbar'
    %main.pb-44{class: "w-[1200px] mt-5 m-auto"}
      .col-start-3.col-span-10= yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Alcaravan
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body.bg-login
    %main
      .col-start-3.col-span-10= yield

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  %body
    = yield